apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci
  labels:
    app: fibonacci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: fibonacci
    spec:
      containers:
      - name: fibonacci
        image: fibonacci:latest
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100m
          requests:
            cpu: 100m
            memory: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    nodePort: 30010
  selector:
    app: fibonacci