  apiVersion: v1
    kind: pod
    metadata:
      name: test
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            run: test
        spec:
          containers:
          - name: test
            image: test:latest
            ports:
            - containerPort: 80