apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
  namespace: teastore
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: teastore
  template:
    metadata:
      labels:
        app: teastore
      namespace: default
    spec:
      containers:
        - image: angi2412/autoscaler
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /heartbeat
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: autoscaler
          ports:
            - containerPort: 5000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaler
  labels:
    app: teastore
    run: autoscaler
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30050
      protocol: TCP
  selector:
    run: autoscaler
