apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-webui
  namespace: teastore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-webui
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metricName: response_time
        targetAverageValue: 1000