name: Release

on:
  milestone:
    types: [closed]
    
jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: 'development'
      - run: echo ::set-env name=VERSION::$(grep -o ".\..\.." <<< "${{ github.event.milestone.title }}")
      - run: sed -i 's/<teastoreversion>.*<\/teastoreversion>/<teastoreversion>${{ env.VERSION }}<\/teastoreversion>/' pom.xml
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Automated version number bump" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: development
          
  mergeDevelop:
    runs-on: ubuntu-latest
    needs: [bumpVersion]
    steps: 
      - run: |
          git clone https://github.com/DescartesResearch/TeaStore.git
          cd TeaStore
          git remote set-url origin https://action:${{ secrets.GITHUB_TOKEN }}@github.com/DescartesResearch/TeaStore.git
          git fetch origin
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git merge origin/development -m "Automated merge in preparation of release"
          git push
          
  createRelease:
    runs-on: ubuntu-latest
    needs: [mergeDevelop]
    steps:
      - run: echo ::set-env name=VERSION::$(grep -o ".\..\.." <<< "${{ github.event.milestone.title }}")
      - uses: actions/checkout@master
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.VERSION }}
          release_name: ${{ github.event.milestone.title }}
          body: ${{ github.event.milestone.description }}
          
  publishDocker:
    runs-on: ubuntu-latest
    needs: [createRelease]
    steps: 
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
      - run: git pull
      - run: echo ::set-env name=VERSION::$(grep -o ".\..\.." <<< "${{ github.event.milestone.title }}")
      - run: mvn clean install
        
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-base
          file: utilities/tools.descartes.teastore.dockerbase/Dockerfile
          path: utilities/tools.descartes.teastore.dockerbase
          tags: ${{ env.VERSION }},latest
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-recommender
          file: services/tools.descartes.teastore.recommender/Dockerfile
          path: services/tools.descartes.teastore.recommender
          tags: ${{ env.VERSION }},latest
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-webui
          file: services/tools.descartes.teastore.webui/Dockerfile
          path: services/tools.descartes.teastore.webui
          tags: ${{ env.VERSION }},latest
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-image
          file: services/tools.descartes.teastore.image/Dockerfile
          path: services/tools.descartes.teastore.image
          tags: ${{ env.VERSION }},latest
              
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-auth
          file: services/tools.descartes.teastore.auth/Dockerfile
          path: services/tools.descartes.teastore.auth
          tags: ${{ env.VERSION }},latest
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-persistence
          file: services/tools.descartes.teastore.persistence/Dockerfile
          path: services/tools.descartes.teastore.persistence
          tags: ${{ env.VERSION }},latest
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-registry
          file: services/tools.descartes.teastore.registry/Dockerfile
          path: services/tools.descartes.teastore.registry
          tags: ${{ env.VERSION }},latest
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-db
          file: utilities/tools.descartes.teastore.database/Dockerfile
          path: utilities/tools.descartes.teastore.database
          tags: ${{ env.VERSION }},latest
          
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-kieker-rabbitmq
          file: utilities/tools.descartes.teastore.kieker.rabbitmq/Dockerfile
          path: utilities/tools.descartes.teastore.kieker.rabbitmq
          tags: ${{ env.VERSION }},latest
